export const COLLECT_VIDEO = 'COLLECT_VIDEO'

export const CANCEL_COLLECT_VIDEO = 'CANCEL_COLLECT_VIDEO'

export const ADD_VIDEO_RECORD = 'ADD_VIDEO_RECORD'

export const DELETE_VIDEO_RECORD_BY_KEY = 'DELETE_VIDEO_RECORD_BY_KEY'

export const ADD_STORAGE_FILE_NAME = 'ADD_STORAGE_FILE_NAME'

export const DELETE_STORAGE_FILE_NAME = 'DELETE_STORAGE_FILE_NAME'

export const SET_CURRENT_STORAGE_FILE_NAME = 'SET_CURRENT_STORAGE_FILE_NAME'
		