export const COLLECT_VIDEO = 'COLLECT_VIDEO'

export const CANCEL_COLLECT_VIDEO = 'CANCEL_COLLECT_VIDEO'

export const ADD_VIDEO_RECORD = 'ADD_VIDEO_RECORD'

export const DELETE_VIDEO_RECORD_BY_KEY = 'DELETE_VIDEO_RECORD_BY_KEY'

export const ADD_SEARCH_KEY = 'ADD_SEARCH_KEY'

export const CLEAR_SEARCH_RECORD = 'CLEAR_SEARCH_RECORD'
