export const SET_MY_CHANNEL_LIST_DATA = 'SET_MY_CHANNEL_LIST_DATA'

export const ADD_TAG_TO_MY_CHANNEL_LIST = 'ADD_TAG_TO_MY_CHANNEL_LIST'

export const REMOVE_TAG_FROM_MY_CHANNEL_LIST = 'REMOVE_TAG_FROM_MY_CHANNEL_LIST'

export const SET_ALL_CHANNEL_LIST_DATA = 'SET_ALL_CHANNEL_LIST_DATA'

export const ADD_TAG_TO_All_CHANNEL_LIST = 'ADD_TAG_TO_All_CHANNEL_LIST'

export const REMOVE_TAG_FROM_All_CHANNEL_LIST = 'REMOVE_TAG_FROM_All_CHANNEL_LIST'
